name: .NET Core (TESTE)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.0.1        
                
    - name: Build com o utilitario dotnet
      run: dotnet build ../LoteriasBrasileiras/ --configuration Release
